# Generated by Django 2.2.10 on 2021-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, verbose_name='每次一杯水')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始喝水')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='喝完一杯水')),
                ('water', models.IntegerField(default=1, verbose_name='今日第几杯水')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
