# Generated by Django 2.2.10 on 2021-07-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_auto_20210707_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waterinfo',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='喝完一杯水'),
        ),
    ]
